// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef RESULTADO_SIMULACAO_ODB_HXX
#define RESULTADO_SIMULACAO_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "ResultadoSimulacao.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>

#include <odb/details/unused.hxx>

namespace odb
{
  // ResultadoSimulacao
  //
  template <>
  struct class_traits< ::simulacao::ResultadoSimulacao >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::simulacao::ResultadoSimulacao >
  {
    public:
    typedef ::simulacao::ResultadoSimulacao object_type;
    typedef ::simulacao::ResultadoSimulacao* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>

namespace odb
{
  // ResultadoSimulacao
  //
  template <>
  class access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >:
    public access::object_traits< ::simulacao::ResultadoSimulacao >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // largura
      //
      double largura_value;
      bool largura_null;

      // comprimento
      //
      double comprimento_value;
      bool comprimento_null;

      // pessoas
      //
      long long pessoas_value;
      bool pessoas_null;

      // televisoes
      //
      long long televisoes_value;
      bool televisoes_null;

      // computadores
      //
      long long computadores_value;
      bool computadores_null;

      // celulares
      //
      long long celulares_value;
      bool celulares_null;

      // solDireto
      //
      long long solDireto_value;
      bool solDireto_null;

      // btu
      //
      double btu_value;
      bool btu_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_common >:
    public access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >
  {
  };
}

#include "ResultadoSimulacao-odb.ixx"

#include <odb/post.hxx>

#endif // RESULTADO_SIMULACAO_ODB_HXX
