/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "ResultadoSimulacao";

CREATE TABLE "ResultadoSimulacao" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "btu" REAL NULL);

