// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "ResultadoSimulacao-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>

namespace odb
{
  // ResultadoSimulacao
  //

  struct access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::id_type
  access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = false;

    // largura
    //
    t[1UL] = false;

    // comprimento
    //
    t[2UL] = false;

    // pessoas
    //
    t[3UL] = false;

    // televisoes
    //
    t[4UL] = false;

    // computadores
    //
    t[5UL] = false;

    // celulares
    //
    t[6UL] = false;

    // solDireto
    //
    t[7UL] = false;

    // btu
    //
    t[8UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // largura
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.largura_value;
    b[n].is_null = &i.largura_null;
    n++;

    // comprimento
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.comprimento_value;
    b[n].is_null = &i.comprimento_null;
    n++;

    // pessoas
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.pessoas_value;
    b[n].is_null = &i.pessoas_null;
    n++;

    // televisoes
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.televisoes_value;
    b[n].is_null = &i.televisoes_null;
    n++;

    // computadores
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.computadores_value;
    b[n].is_null = &i.computadores_null;
    n++;

    // celulares
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.celulares_value;
    b[n].is_null = &i.celulares_null;
    n++;

    // solDireto
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.solDireto_value;
    b[n].is_null = &i.solDireto_null;
    n++;

    // btu
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.btu_value;
    b[n].is_null = &i.btu_null;
    n++;
  }

  void access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // id
    //
    if (sk == statement_insert)
    {
      int const& v =
        o.id;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        v);
      i.id_null = is_null;
    }

    // largura
    //
    {
      double const& v =
        o.largura;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.largura_value,
        is_null,
        v);
      i.largura_null = is_null;
    }

    // comprimento
    //
    {
      double const& v =
        o.comprimento;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.comprimento_value,
        is_null,
        v);
      i.comprimento_null = is_null;
    }

    // pessoas
    //
    {
      int const& v =
        o.pessoas;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.pessoas_value,
        is_null,
        v);
      i.pessoas_null = is_null;
    }

    // televisoes
    //
    {
      int const& v =
        o.televisoes;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.televisoes_value,
        is_null,
        v);
      i.televisoes_null = is_null;
    }

    // computadores
    //
    {
      int const& v =
        o.computadores;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.computadores_value,
        is_null,
        v);
      i.computadores_null = is_null;
    }

    // celulares
    //
    {
      int const& v =
        o.celulares;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.celulares_value,
        is_null,
        v);
      i.celulares_null = is_null;
    }

    // solDireto
    //
    {
      bool const& v =
        o.solDireto;

      bool is_null (false);
      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_image (
        i.solDireto_value,
        is_null,
        v);
      i.solDireto_null = is_null;
    }

    // btu
    //
    {
      double const& v =
        o.btu;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.btu_value,
        is_null,
        v);
      i.btu_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      int& v =
        o.id;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // largura
    //
    {
      double& v =
        o.largura;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.largura_value,
        i.largura_null);
    }

    // comprimento
    //
    {
      double& v =
        o.comprimento;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.comprimento_value,
        i.comprimento_null);
    }

    // pessoas
    //
    {
      int& v =
        o.pessoas;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.pessoas_value,
        i.pessoas_null);
    }

    // televisoes
    //
    {
      int& v =
        o.televisoes;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.televisoes_value,
        i.televisoes_null);
    }

    // computadores
    //
    {
      int& v =
        o.computadores;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.computadores_value,
        i.computadores_null);
    }

    // celulares
    //
    {
      int& v =
        o.celulares;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.celulares_value,
        i.celulares_null);
    }

    // solDireto
    //
    {
      bool& v =
        o.solDireto;

      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_value (
        v,
        i.solDireto_value,
        i.solDireto_null);
    }

    // btu
    //
    {
      double& v =
        o.btu;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.btu_value,
        i.btu_null);
    }
  }

  void access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::persist_statement[] =
  "INSERT INTO \"ResultadoSimulacao\" "
  "(\"id\", "
  "\"largura\", "
  "\"comprimento\", "
  "\"pessoas\", "
  "\"televisoes\", "
  "\"computadores\", "
  "\"celulares\", "
  "\"solDireto\", "
  "\"btu\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::find_statement[] =
  "SELECT "
  "\"ResultadoSimulacao\".\"id\", "
  "\"ResultadoSimulacao\".\"largura\", "
  "\"ResultadoSimulacao\".\"comprimento\", "
  "\"ResultadoSimulacao\".\"pessoas\", "
  "\"ResultadoSimulacao\".\"televisoes\", "
  "\"ResultadoSimulacao\".\"computadores\", "
  "\"ResultadoSimulacao\".\"celulares\", "
  "\"ResultadoSimulacao\".\"solDireto\", "
  "\"ResultadoSimulacao\".\"btu\" "
  "FROM \"ResultadoSimulacao\" "
  "WHERE \"ResultadoSimulacao\".\"id\"=?";

  const char access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::update_statement[] =
  "UPDATE \"ResultadoSimulacao\" "
  "SET "
  "\"largura\"=?, "
  "\"comprimento\"=?, "
  "\"pessoas\"=?, "
  "\"televisoes\"=?, "
  "\"computadores\"=?, "
  "\"celulares\"=?, "
  "\"solDireto\"=?, "
  "\"btu\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::erase_statement[] =
  "DELETE FROM \"ResultadoSimulacao\" "
  "WHERE \"id\"=?";

  void access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.id_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::pointer_type
  access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::simulacao::ResultadoSimulacao, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    return r != select_statement::no_data;
  }
}

#include <odb/post.hxx>
